### PR TITLE
Multiple fixes

### PR DESCRIPTION
**Pull request by english5040**
(WIP, needs testing)

- Fix for alchemical dx/cu duplicates; also general fix for dx/cu duplicate logic
- Fix foiled planets displaying + on the mult
- Compat with Bunco's glitter

### CODE REVIEW

**Comment by JeffVi** [comment]
LGTM

Assuming that no other mod creates a `bunc_glitter` edition without setting up the `bunc_glitter` sound or implementing `G.P_CENTERS.e_bunc_glitter`

**Comment by english5040** [comment]
Testing revealed a bug, whoops, it's now fixed.

This can be merged as-is; next on the list was debuffed card logic but that can be in a separate PR.

**Comment by ChromaPIE** [comment]
now that we got glitter compat how about also bringing cryptid ones here? codes are in dimserene's dx tarots fork but i havent done the compat for black hole/black hole dx.

**Comment by english5040** [comment]
Glitched edition is definitely weird; the glitched edition currently shows random mult/chip values on the planet when hovered, I'd intuitively expect those values to be applied

**Comment by english5040** [comment]
looks like glitched edition has changed again.

**Pull request merged**
